#!/usr/bin/env ruby
# render-registry.rb — render homebase's project registry from per-project YAMLs.
#
# Usage:
#   render-registry.rb <homebase-root>
#
# Reads:  <homebase-root>/registry/projects.paths
#         <each project path>/.homebase/project.yml
# Writes: Markdown to stdout (caller redirects to registry/PROJECTS.md).
#
# Exit codes:
#   0 — rendered cleanly
#   1 — one or more projects missing .homebase/project.yml
#   2 — bad argv, parse error, or schema mismatch

require "yaml"
require "pathname"
require "set"

HOMEBASE = ARGV[0] or abort "usage: render-registry.rb <homebase-root>"
HOMEBASE_DIR = Pathname.new(HOMEBASE).expand_path
PATHS_FILE = HOMEBASE_DIR / "registry" / "projects.paths"

abort "missing: #{PATHS_FILE}" unless PATHS_FILE.file?

REQUIRED_PROJECT_KEYS = %w[name display_name description kind domains apps]
REQUIRED_APP_KEYS = %w[name path platforms status summary]
VALID_STATUS = %w[active research retired planned]
VALID_KIND = %w[monorepo single-app]

def die(msg)
  warn "render-registry: #{msg}"
  exit 2
end

def soft_warn(msg)
  warn "render-registry: WARNING: #{msg}"
end

def validate(doc, path)
  die "#{path}: root must be a map" unless doc.is_a?(Hash)
  missing = REQUIRED_PROJECT_KEYS - doc.keys
  die "#{path}: missing keys: #{missing.join(', ')}" unless missing.empty?
  die "#{path}: kind must be one of #{VALID_KIND}" unless VALID_KIND.include?(doc["kind"])
  die "#{path}: domains must be an array" unless doc["domains"].is_a?(Array)
  die "#{path}: apps must be a non-empty array" unless doc["apps"].is_a?(Array) && !doc["apps"].empty?

  doc["apps"].each_with_index do |app, i|
    die "#{path}: apps[#{i}] must be a map" unless app.is_a?(Hash)
    missing = REQUIRED_APP_KEYS - app.keys
    die "#{path}: apps[#{i}] (#{app["name"]}) missing: #{missing.join(', ')}" unless missing.empty?
    die "#{path}: apps[#{i}] status invalid" unless VALID_STATUS.include?(app["status"])
    die "#{path}: apps[#{i}] platforms must be array" unless app["platforms"].is_a?(Array)
    if app["platforms"].include?("web") && app["status"] == "active" && !app["deploy"].is_a?(Hash)
      soft_warn "#{path}: apps[#{i}] (#{app["name"]}) is web+active but has no deploy: stanza — won't work with `homebase deploy`"
    end
  end

  if doc["brands"]
    die "#{path}: brands must be an array" unless doc["brands"].is_a?(Array)
    brand_ids = doc["brands"].map { |b| b["id"] }.to_set
    doc["apps"].each_with_index do |app, i|
      if app["brand"] && !brand_ids.include?(app["brand"])
        die "#{path}: apps[#{i}] brand '#{app["brand"]}' not declared in brands[]"
      end
    end
  end
end

# Load all declarations.
paths = PATHS_FILE.each_line.map(&:strip).reject { |l| l.empty? || l.start_with?("#") }
missing = []
projects = []

paths.each do |p|
  yml = Pathname.new(p) / ".homebase" / "project.yml"
  unless yml.file?
    missing << p
    next
  end
  doc = YAML.safe_load(yml.read, permitted_classes: [], aliases: false)
  validate(doc, yml.to_s)
  projects << { path: Pathname.new(p).expand_path, doc: doc }
end

projects.sort_by! { |e| e[:doc]["name"] }

# Render.
out = String.new

out << "# Project Registry\n\n"
out << "Generated by `bin/homebase index` from each project's `.homebase/project.yml`.\n"
out << "Do not hand-edit — edit the per-project YAML and re-run `bin/homebase index`.\n\n"

projects.each do |entry|
  doc = entry[:doc]
  path = entry[:path]
  name = doc["name"]
  display = doc["display_name"]
  description = doc["description"]
  kind = doc["kind"]
  domains = doc["domains"].join(", ")
  has_brands = doc["brands"].is_a?(Array) && !doc["brands"].empty?

  header_path = path.to_s.sub(ENV["HOME"] || "", "~")
  out << "## #{name} — #{display}\n\n"
  out << "`#{header_path}` · #{kind} · domains: #{domains}\n\n"
  out << "#{description}\n\n"

  if has_brands
    brand_list = doc["brands"].map { |b| b["display_name"] }.join(" · ")
    out << "Brands: #{brand_list}\n\n"
    out << "| App | Path | Platforms | Status | Brand | Summary |\n"
    out << "|---|---|---|---|---|---|\n"
    doc["apps"].each do |app|
      brand_name = if app["brand"]
        b = doc["brands"].find { |br| br["id"] == app["brand"] }
        b ? b["display_name"] : app["brand"]
      else
        "—"
      end
      out << "| #{app["name"]} | #{app["path"]} | #{app["platforms"].join(", ")} | #{app["status"]} | #{brand_name} | #{app["summary"]} |\n"
    end
  else
    out << "| App | Path | Platforms | Status | Summary |\n"
    out << "|---|---|---|---|---|\n"
    doc["apps"].each do |app|
      out << "| #{app["name"]} | #{app["path"]} | #{app["platforms"].join(", ")} | #{app["status"]} | #{app["summary"]} |\n"
    end
  end
  out << "\n"

  if doc["notes"]
    out << "_#{doc["notes"]}_\n\n"
  end
end

# Alias Index
rows = []
projects.each do |entry|
  doc = entry[:doc]
  root = entry[:path]
  doc["apps"].each do |app|
    canonical = app["path"] == "." ? root : (root / app["path"])
    canonical_display = canonical.to_s.sub(ENV["HOME"] || "", "~")
    names = [app["name"]]
    names.concat(app["aliases"]) if app["aliases"].is_a?(Array)
    names.uniq.each do |n|
      rows << [n, canonical_display]
    end
  end
end

if !rows.empty?
  out << "## Alias Index\n\n"
  out << "Quick lookup: app name / alias → absolute path.\n\n"
  out << "| Query | Resolves to |\n"
  out << "|---|---|\n"
  rows.sort_by { |r| r[0].downcase }.each do |q, p|
    out << "| #{q} | `#{p}` |\n"
  end
  out << "\n"
end

print out

exit(missing.empty? ? 0 : 1)
